name: bme590
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - brotli=1.2.0=hca488c2_0
  - brotli-bin=1.2.0=hce9b42c_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - contourpy=1.3.2=py310h7f4e7e6_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - expat=2.7.3=h982b769_0
  - fontconfig=2.14.2=h82840c6_0
  - fonttools=4.60.1=py310hf4fd40f_0
  - freetype=2.14.1=hce30654_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - gettext=0.25.1=h3dcc1bd_0
  - gettext-tools=0.25.1=h493aca8_0
  - greenlet=3.2.4=py310h1af2607_1
  - icu=75.1=hfee45f7_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py310h563d721_2
  - krb5=1.21.3=h237132a_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libasprintf=0.25.1=h493aca8_0
  - libasprintf-devel=0.25.1=h493aca8_0
  - libblas=3.9.0=39_h51639a9_openblas
  - libboost=1.86.0=h29978a0_2
  - libboost-python=1.86.0=py310hdc87794_4
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.9.0=39_hb0561ab_openblas
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=hd74edd7_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgettextpo=0.25.1=h493aca8_0
  - libgettextpo-devel=0.25.1=h493aca8_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.2=hc919400_0
  - liblapack=3.9.0=39_hd9741b5_openblas
  - libntlm=1.8=h5505292_0
  - libopenblas=0.3.30=openmp_ha158390_3
  - libpng=1.6.50=h280e0eb_1
  - libpq=18.0=h31f7a3a_0
  - librdkit=2025.09.2=hab8bf10_1
  - libsqlite=3.51.0=h8adb53f_0
  - libtiff=4.7.0=hfce79cd_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.5=h4a912ad_2
  - matplotlib-base=3.10.8=py310h0181960_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - openjpeg=2.5.3=h889cd5d_1
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py310h25f4b65_1
  - pcre2=10.46=h7125dd6_0
  - pillow=11.3.0=py310h5de80a5_3
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h81086ad_1
  - pthread-stubs=0.4=hd74edd7_1002
  - pycairo=1.27.0=py310h706757e_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.10.15=hdce6c4c_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=8_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h420ef59_5
  - readline=8.3=h0b18652_0
  - reportlab=4.4.4=py310hfe3a0ae_0
  - rlpycairo=0.4.0=pyh6c17108_0
  - scipy=1.15.2=py310h32ab4ed_0
  - setuptools=80.9.0=py310hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlalchemy=2.0.44=py310hfe3a0ae_0
  - sqlite=3.51.0=hab6afd1_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hcd8a7d5_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=17.0.0=py310hfe3a0ae_1
  - wheel=0.45.1=py310hca03da5_0
  - xorg-libxau=1.0.12=hc919400_1
  - xorg-libxdmcp=1.1.5=hc919400_1
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - alembic==1.17.2
      - annotated-types==0.7.0
      - ase==3.26.0
      - asttokens==3.0.1
      - bibtexparser==1.4.3
      - certifi==2025.11.12
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - colorlog==6.10.1
      - decorator==5.2.1
      - deep-forest==0.1.7
      - deprecated==1.3.1
      - descriptastorus==2.6.1
      - docstring-parser==0.17.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - future==1.0.0
      - graphdot==0.8.1
      - hyperopt==0.2.7
      - idna==3.11
      - iniconfig==2.3.0
      - ipython==8.37.0
      - jedi==0.19.2
      - mako==1.3.10
      - markupsafe==3.0.3
      - matplotlib-inline==0.2.1
      - mendeleev==0.19.0
      - mgktools==3.1.0
      - molalkit==1.0.0
      - monty==2025.3.3
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - narwhals==2.12.0
      - networkx==3.4.2
      - numpy==1.26.4
      - optuna==4.6.0
      - orjson==3.11.4
      - palettable==3.3.3
      - pandas-flavor==0.7.0
      - parso==0.8.5
      - pexpect==4.9.0
      - plotly==6.4.0
      - pluggy==1.6.0
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py4j==0.10.9.9
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyfiglet==0.8.post1
      - pygments==2.19.2
      - pymatgen==2025.10.7
      - pytest==9.0.1
      - pyyaml==6.0.3
      - rdkit==2023.9.6
      - requests==2.32.5
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.15
      - rxntools==0.0.2
      - scikit-learn==1.5.2
      - selfies==2.2.0
      - spglib==2.6.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - tomli==2.3.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - treelib==1.8.0
      - typed-argument-parser==1.11.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - uncertainties==3.2.3
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - wrapt==2.0.1
      - xarray==2025.6.1
      - xgboost==3.1.1
prefix: /opt/miniconda3/envs/bme590
